{% set version = "0.0.16" %}
{% set python_min = "3.10" %}

package:
  name: mutt-language-server
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/m/mutt-language-server/mutt_language_server-{{ version }}.tar.gz
  sha256: 27a4ad11d954b3c028f3449674db6f52e62f9ae15866e641d9fbb145cbdbd47d

build:
  entry_points:
    - mutt-language-server = mutt_language_server.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - setuptools-generate >=0.0.6
    - pip
  run:
    - python >={{ python_min }}
    - lsp-tree-sitter
    - tree-sitter-muttrc >=0.0.4

test:
  imports:
    - mutt_language_server
  commands:
    - pip check
    - mutt-language-server --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/neomutt/mutt-language-server
  summary: mutt language server
  dev_url: https://github.com/neomutt/mutt-language-server
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
